$if[$message==botlist/canais/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais.ruby
$elseif[$message==botlist/cargos/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos.ruby

$elseif[$message==botlist/canais/addbot/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Modal/Addbot.ruby
$elseif[$customID==modal/canal/addbot]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Enviar%20Modal/Addbot.ruby
$elseif[$message==botlist/canais/correios/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Modal/Correios.ruby
$elseif[$customID==modal/canal/correios]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Enviar%20Modal/Correios.ruby
$elseif[$message==botlist/canais/análises/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Modal/Análises.ruby
$elseif[$customID==modal/canal/análises]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Enviar%20Modal/Análises.ruby
$elseif[$message==botlist/canais/logs-bot/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Modal/Logs-Bot.ruby
$elseif[$customID==modal/canal/logs-bot]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Enviar%20Modal/Logs-Bot.ruby
$elseif[$message==botlist/canais/logs-votos/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Modal/Logs-Votos.ruby
$elseif[$customID==modal/canal/logs-votos]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Enviar%20Modal/Logs-Votos.ruby
$elseif[$message==botlist/canais/categoria-top-3/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Modal/Top-3-Bots.ruby
$elseif[$customID==modal/canal/categoria-top-3]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Canais/Enviar%20Modal/Top-3-Bots.ruby

$elseif[$message==botlist/cargos/bot-em-análise/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Modal/Bot-em-An%C3%A1lise.ruby
$elseif[$customID==modal/cargo/bot-em-análise]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Enviar%20Modal/Bot-em-An%C3%A1lise.ruby
$elseif[$message==botlist/cargos/bot-análisado/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Modal/Bot-An%C3%A1lisado.ruby
$elseif[$customID==modal/cargo/bot-análisado]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Modal/Bot-An%C3%A1lisado.ruby
$elseif[$message==botlist/cargos/developer/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Modal/Developer.ruby
$elseif[$customID==modal/cargo/developer]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Enviar%20Modal/Developer.ruby
$elseif[$message==botlist/cargos/análisadores/$authorID]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Modal/An%C3%A1lisadores.ruby
$elseif[$customID==modal/cargo/análisadores]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botlist/Cargos/Enviar%20Modal/An%C3%A1lisadores.ruby

$elseif[$and[$textSplit[$message;/]$splitText[1]==botinfo;$splitText[2]==inicio;$splitText[3]==$authorID]==true]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Utilidade/Botinfo.ruby
$elseif[$and[$textSplit[$message;/]$splitText[1]==botinfo;$splitText[2]==sobre-mim;$splitText[3]==$authorID]==true]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Utilidade/Intera%C3%A7%C3%B5es/Botinfo/Mais.ruby
$elseif[$and[$textSplit[$message;/]$splitText[1]==botinfo;$splitText[2]==developers;$splitText[3]==$authorID]==true]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Utilidade/Intera%C3%A7%C3%B5es/Botinfo/Developers.ruby

$elseif[$and[$textSplit[$customID;/]$splitText[1]==daily;$splitText[2]==$authorID]==true]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Economia/Intera%C3%A7%C3%B5es/Daily.ruby
$elseif[$and[$textSplit[$customID;/]$splitText[1]==slot;$splitText[4]==$authorID]==true]
https://raw.githubusercontent.com/Demom23345/Quazar/main/Comandos/Economia/Intera%C3%A7%C3%B5es/Slot.ruby
$endif
